version: '3.9'
services:
  db:
    image: postgres:15
    container_name: shop-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopdb
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432" 